# Generated by Django 5.0.7 on 2024-08-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex_Account_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Name', models.CharField(max_length=50)),
                ('Email_Address', models.CharField(max_length=50)),
                ('Login', models.CharField(max_length=15)),
                ('Trading_Password', models.IntegerField()),
                ('Meta_Trader', models.CharField(max_length=15)),
            ],
        ),
    ]
