# Generated by Django 5.0.7 on 2024-08-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_App', '0002_forex_account_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex_account_management',
            name='Login',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forex_account_management',
            name='Trading_Password',
            field=models.CharField(max_length=15),
        ),
    ]
