# Generated by Django 5.1 on 2024-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_App', '0004_fx_account_mgt_delete_forex_account_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formfxfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Login', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
