# Generated by Django 5.1 on 2024-09-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_customerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade4me_Form',
            new_name='Trade4me',
        ),
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
